import {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {SidebarProvider} from "@/components/ui/sidebar";
import AppSidebar from "@/components/AppSidebar";
import Navbar from "@/components/Navbar";
import {ThemeProvider} from "@/components/themeProvider";
import {Toaster} from "@/components/ui/sonner";
import {getEmployees} from "@/api/getEmployees";
import {getDepartments} from "@/api/getDepartments";
import Hydrator from "@/components/Hydrator";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Lotus Dashboard",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const [employees, departments] = await Promise.all([
        getEmployees(),
        getDepartments(),
    ]);

    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Hydrator employees={employees} departments={departments}/>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <SidebarProvider defaultOpen={true}>
                <AppSidebar/>
                <main className="w-full">
                    <Navbar/>
                    <div className="p-4">{children}</div>
                </main>
            </SidebarProvider>
        </ThemeProvider>
        <Toaster/>
        </body>
        </html>
    );
}